added ignoring of busybox tar errors

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -894,7 +894,9 @@ extract_deb_data () {
 	esac
 
 	if type $cat_cmd >/dev/null 2>&1; then
-		"$DEBOOTSTRAP_AR" -p "$pkg" "$tarball" | $cat_cmd | tar -xf -
+		# Ignoring errors in tar because mawk_1.3.3-2_i386.deb in
+		# Debian slink causes a short read, which busybox tar fails on.
+		"$DEBOOTSTRAP_AR" -p "$pkg" "$tarball" | $cat_cmd | tar -xf - ||:
 	else
 		error 1 UNPACKCMDUNVL "Extracting %s requires the %s command, which is not available" "$pkg" "$cat_cmd"
 	fi
